# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [5]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape       # 1차원 == (4, )

(dtype('float64'), (4,))

## 2. Array shape

In [14]:
# Vector (1차원 데이터)           # 1차원 == (4, )
vector = np.array([1, 4, 5, 8])
vector.shape

(4,)

In [10]:
# Matrix (2차원 데이터)            # 2차원 == (2,3)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.shape)
print(matrix)


(2, 3)
[[1 2 3]
 [4 5 6]]


In [11]:
# Tensor(3차원 이상)               # 3차원 == (2,3,4)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
tensor.shape

(2, 3, 4)

In [15]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [17]:
# element의 갯수
vector.size, matrix.shape, tensor.shape

(4, (2, 3), (2, 3, 4))

In [19]:
# data type
# float32: 32bit 로 표시 - single precision
# float64: 64bit 로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [20]:
b = np.array([1,2,3], dtype=np.int16)        # int32 가 default 값
b

array([1, 2, 3], dtype=int16)

### reshape

In [21]:
matrix.shape

(2, 3)

In [22]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [23]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [25]:
matrix.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
matrix.reshape(3,-1).shape

(3, 2)

In [27]:
tensor.reshape(4,-1).shape

(4, 6)

In [28]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [30]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [31]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### flatten

In [39]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [33]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [35]:
matrix.shape

(2, 3)

In [36]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
matrix[0][1]    ## [행][열]

2

In [38]:
matrix[0,1]     ## [행,열]

2

In [40]:
tensor[1,1,2]   ## [면,행,열]

19

### Slicing

In [41]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
# 5, 6, 9, 10 꺼내기
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [45]:
# 5, 6, 7, 9, 10, 11 꺼내기
b[1:3, 1:]           ## 1: 1번째부터 끝까지

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [47]:
# 1, 3, 9, 11 꺼내기
b[::2, 1::2]          ## ::2 처음부터 끝까지 2칸 건너뛰기 /1::2 1번째부터 2칸 건너뛰기

array([[ 1,  3],
       [ 9, 11]])

In [48]:
# X 는 앞에 3열, y 는 마지막 열
X, y = b[:, :-1], b[:,-1]         
X.shape, y.shape

((4, 3), (4,))