# Q1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
### 10 20 30 40
### 50 60 70 80

In [2]:
import numpy as np
a = np.array([(10,20,30,40), (50,60,70,80)])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [11]:
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# Q2. 다음 행렬과 같은 행렬이 있다


In [ ]:
###
m =
np.array ([[ 0, 1, 2, 3, 4],
           [ 5, 6, 7, 8, 9],
           [10, 11, 12, 13, 14]],)
###

In [6]:
import numpy as np
a = np.array([(0,1,2,3,4), (5,6,7,8,9), (10,11,12,13,14)], int)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 1. 이 행렬에서 값 7을 인덱싱한다.

In [7]:
print(a[1,2])

7


### 2. 이 행렬에서 값 14 을 인덱싱한다.

In [8]:
print(a[2,4])

14


### 3. 이 행렬에서 배열 [6,7] 을 슬라이싱한다.

In [9]:
a[1, 1:3]

array([6, 7])

### 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다

In [14]:
a[1:, 2]

array([ 7, 12])

### 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다


In [15]:
a[:2, 3:]

array([[3, 4],
       [8, 9]])

# Q3. 2 번의 행렬 m 을 1 차원 벡터 f 로 변환한 후 다음의 문제를 푸시오
- Boolean Indexing

In [16]:
f = a.flatten()

### 1. 이 배열에서 3 의 배수를 찾아라

In [17]:
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

### 2. 이 배열에서 4 로 나누면 1 이 남는 수를 찾아라

In [18]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

### 3. 이 배열에서 3 으로 나누면 나누어지고 4 로 나누면 1 이 남는 수를 찾아라

In [20]:
f[np.logical_and(f % 3 == 0, f % 4 == 1)]

array([9])

# Q4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오.
- eye로 행렬 만들기

In [21]:
np.eye(5,5,k=-1) * 3 + np.eye(5,5) * 2 + np.eye(5,5,k=1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

# Q5. 0 에서 10 까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오

In [24]:
np.random.seed(2021)
b = np.random.uniform(0,10,30).reshape(5,6)
b

array([[6.05978279, 7.33369361, 1.38947157, 3.12673084, 9.97243281,
        1.28162375],
       [1.78993106, 7.52925429, 6.62160514, 7.84310132, 0.96894396,
        0.58571285],
       [9.6239599 , 6.16557444, 0.86629961, 5.61272363, 6.16524709,
        9.63843023],
       [5.74304294, 3.71160848, 4.52145244, 2.01850248, 5.69305118,
        1.95095974],
       [5.83704016, 4.76313474, 5.178144  , 8.23098634, 7.32225027,
        0.69056275]])

In [25]:
np.random.seed(2021)
b = np.random.uniform(0,10,30).reshape(5,6).round(4)
b

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

### 1. 전체의 최댓값

In [26]:
np.max(b)

9.9724

### 2. 각 행의 합

In [27]:
np.sum(b, axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

### 3. 각 행의 최댓값

In [29]:
np.max(b, axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

### 4. 각 열의 평균

In [30]:
np.mean(b, axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

### 5. 각 열의 최솟값

In [31]:
np.min(b, axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

# Q6. 다음 배열은 첫번째 행 ( 에 학번 , 두번째 행에 영어 성적 , 세번째 행에 수학 성적을 적은 배열이다 . 영어 성적을 기준으로 각 열 ( 을 재정렬하시오
- Sorting

In [32]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [33]:
np.sort(score)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [34]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [35]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [38]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [40]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

# Q7. 주사위를 100 번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오

In [41]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [42]:
np.mean(dice)

3.7

In [43]:
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

# Q8. 가격이 10,000 원인 주식이 있다 . 이 주식의 일간 수익률 은 기댓값이 0% 이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자 . 250 일 동안의 주가를 무작위로 생성하시오